### ISSUE TITLE
Remove image that you don't have copyright to

### ISSUE THREAD

**Issue by OmgImAlexis** [gdomaradzki/focus-budget-manager#22]
To prevent this repo being taken down with a DMCA I'd suggest you replace the image found [here](https://github.com/gdomaradzki/focus-budget-manager/tree/master/application/src/assets/images) with a free one from [pexels](https://www.pexels.com).

**Comment by gdomaradzki** [comment]
Thank you Alexis for reaching out and providing a good source for free images. I'll replace it as soon as possible.
